### ISSUE TITLE
Shows me as friend with my self and not my friends

### ISSUE THREAD

**Issue by znichola** [0xOnyx/42_ft_transcendence#80]
<img width="1012" alt="Screen Shot 2023-05-13 at 3 26 05 PM" src="https://github.com/0xOnyx/42_ft_transcendence/assets/12100623/32c82e30-b4d1-46a2-8906-657339f47746">

**Comment by znichola** [comment]
here also 
<img width="956" alt="Screen Shot 2023-05-13 at 3 34 19 PM" src="https://github.com/0xOnyx/42_ft_transcendence/assets/12100623/464eb3f6-99d9-4e5d-a1a1-972523ce7bd2">

**Comment by danielthalmann** [comment]
thanks for report ! 
This problem is know.
We have make a fix.
